In [26]:
import numpy as np

m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
k = int(input())
for i in range (len(m)):
    for j in range(len(m[i])):
        if int(i + 1) % k == 0 and int(j + 1) % k == 0:
            m[i][j] = 0
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [27]:
import numpy as np

m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
k = int(input())
for i in range (len(m)):
    for j in range(len(m[i])):
        if int(i + 1) % k == 0 and int(j + 1) % k == 0:
            m[i][j] *= 2 
print(m)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 18]]


In [51]:
m = np.array([[3, 2], [5, 6], [7, 1]])
#([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
lst = [[] for i in range(len(m[0]))]
for i in range (len(m)):
    for j in range(len(m[i])):
        lst[j].append(m[i][j])
m = np.empty(len(m[0]))
for i in range(len(lst)):
    m[i] = int(max(lst[i]) - min(lst[i]))
print (m)

[4. 5.]


In [58]:
x = np.array([[3,4],[5,12],[24,7]])
y = np.array([int((i[0]**2 + i[1]**2)**(1/2)) for i in x])
print(y)

[ 5 13 25]


In [64]:
k = int(input())
c = np.array([[(i+j)%2 for j in range(k)]for i in range(k)])
print(c)

[[0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]]


In [66]:
k = int(input())
c = np.array([[i+1 if(i+j)%2==0 else 0 for j in range(k)]for i in range(k)])
print(c)

[[1 0 1 0 1]
 [0 2 0 2 0]
 [3 0 3 0 3]
 [0 4 0 4 0]
 [5 0 5 0 5]]
